// Ingredient catalog with typical shelf lives (days) per storage location.
// Used to auto-fill expiry dates when items are added without one.
// Format: [name, category, defaultUnit, pantryDays, fridgeDays, freezerDays]

export type CatalogEntry = [
  name: string,
  category: string,
  defaultUnit: string,
  pantry: number | null,
  fridge: number | null,
  freezer: number | null,
];

export const CATALOG: CatalogEntry[] = [
  // — produce —
  ["spinach", "produce", "g", null, 5, 240],
  ["arugula", "produce", "g", null, 5, null],
  ["kale", "produce", "g", null, 7, 240],
  ["romaine lettuce", "produce", "each", null, 7, null],
  ["cabbage", "produce", "each", null, 30, null],
  ["tomatoes", "produce", "each", 5, 8, null],
  ["cherry tomatoes", "produce", "g", 4, 7, null],
  ["cucumber", "produce", "each", null, 7, null],
  ["bell pepper", "produce", "each", null, 10, 240],
  ["zucchini", "produce", "each", null, 7, 240],
  ["eggplant", "produce", "each", null, 7, null],
  ["broccoli", "produce", "each", null, 7, 300],
  ["cauliflower", "produce", "each", null, 10, 300],
  ["carrots", "produce", "g", null, 21, 300],
  ["celery", "produce", "each", null, 14, null],
  ["green beans", "produce", "g", null, 7, 240],
  ["asparagus", "produce", "bunch", null, 4, 240],
  ["mushrooms", "produce", "g", null, 7, null],
  ["corn", "produce", "ear", null, 3, 240],
  ["avocado", "produce", "each", 4, 7, null],
  ["banana", "produce", "each", 5, null, 60],
  ["apples", "produce", "each", 7, 30, null],
  ["lemons", "produce", "each", 10, 21, null],
  ["limes", "produce", "each", 10, 21, null],
  ["oranges", "produce", "each", 10, 21, null],
  ["strawberries", "produce", "g", null, 4, 240],
  ["blueberries", "produce", "g", null, 7, 240],
  ["grapes", "produce", "g", null, 10, null],
  ["onion", "produce", "each", 30, null, null],
  ["red onion", "produce", "each", 30, null, null],
  ["garlic", "produce", "each", 60, null, null],
  ["ginger", "produce", "each", 7, 21, 90],
  ["potatoes", "produce", "each", 30, null, null],
  ["sweet potatoes", "produce", "each", 21, null, null],
  ["scallions", "produce", "bunch", null, 7, null],
  ["fresh basil", "produce", "bunch", null, 4, null],
  ["cilantro", "produce", "bunch", null, 6, null],
  ["parsley", "produce", "bunch", null, 7, null],
  ["fresh dill", "produce", "bunch", null, 5, null],
  ["fresh thyme", "produce", "bunch", null, 10, null],
  ["rosemary", "produce", "bunch", null, 10, null],
  ["frozen peas", "produce", "g", null, null, 300],

  // — dairy & eggs —
  ["eggs", "dairy & eggs", "each", null, 28, null],
  ["milk", "dairy & eggs", "ml", null, 7, null],
  ["heavy cream", "dairy & eggs", "ml", null, 10, null],
  ["butter", "dairy & eggs", "g", null, 60, 240],
  ["greek yogurt", "dairy & eggs", "g", null, 14, null],
  ["sour cream", "dairy & eggs", "g", null, 14, null],
  ["cream cheese", "dairy & eggs", "g", null, 21, null],
  ["cheddar", "dairy & eggs", "g", null, 30, 180],
  ["fresh mozzarella", "dairy & eggs", "g", null, 7, null],
  ["parmesan", "dairy & eggs", "g", null, 60, null],
  ["feta", "dairy & eggs", "g", null, 21, null],
  ["ricotta", "dairy & eggs", "g", null, 7, null],
  ["tofu", "dairy & eggs", "g", null, 7, 120],

  // — meat & fish —
  ["chicken breast", "meat & fish", "g", null, 2, 270],
  ["chicken thighs", "meat & fish", "g", null, 2, 270],
  ["ground beef", "meat & fish", "g", null, 2, 120],
  ["ground turkey", "meat & fish", "g", null, 2, 120],
  ["pork chops", "meat & fish", "g", null, 3, 180],
  ["bacon", "meat & fish", "g", null, 7, 30],
  ["italian sausage", "meat & fish", "g", null, 2, 60],
  ["deli ham", "meat & fish", "g", null, 5, 60],
  ["salmon fillet", "meat & fish", "g", null, 2, 90],
  ["cod fillet", "meat & fish", "g", null, 2, 180],
  ["shrimp", "meat & fish", "g", null, 2, 180],

  // — bakery —
  ["bread", "bakery", "loaf", 4, 7, 90],
  ["tortillas", "bakery", "each", 7, 30, 90],
  ["pizza dough", "bakery", "each", null, 3, 90],

  // — pantry —
  ["rice", "pantry", "g", 720, null, null],
  ["arborio rice", "pantry", "g", 720, null, null],
  ["dried pasta", "pantry", "g", 720, null, null],
  ["quinoa", "pantry", "g", 720, null, null],
  ["rolled oats", "pantry", "g", 365, null, null],
  ["flour", "pantry", "g", 365, null, null],
  ["sugar", "pantry", "g", 720, null, null],
  ["panko breadcrumbs", "pantry", "g", 180, null, null],
  ["canned tomatoes", "pantry", "can", 720, null, null],
  ["tomato paste", "pantry", "g", 540, null, null],
  ["coconut milk", "pantry", "can", 720, null, null],
  ["chickpeas", "pantry", "can", 720, null, null],
  ["black beans", "pantry", "can", 720, null, null],
  ["lentils", "pantry", "g", 720, null, null],
  ["chicken stock", "pantry", "ml", 365, 5, null],
  ["kalamata olives", "pantry", "g", 365, 90, null],
  ["peanut butter", "pantry", "g", 270, null, null],
  ["honey", "pantry", "g", 720, null, null],
  ["maple syrup", "pantry", "ml", 365, 365, null],

  // — condiments & spices —
  ["olive oil", "condiments & spices", "ml", 540, null, null],
  ["vegetable oil", "condiments & spices", "ml", 365, null, null],
  ["sesame oil", "condiments & spices", "ml", 365, null, null],
  ["soy sauce", "condiments & spices", "ml", 720, null, null],
  ["fish sauce", "condiments & spices", "ml", 720, null, null],
  ["rice vinegar", "condiments & spices", "ml", 720, null, null],
  ["red wine vinegar", "condiments & spices", "ml", 720, null, null],
  ["balsamic vinegar", "condiments & spices", "ml", 720, null, null],
  ["dijon mustard", "condiments & spices", "g", null, 180, null],
  ["mayonnaise", "condiments & spices", "g", null, 90, null],
  ["sriracha", "condiments & spices", "ml", 365, 365, null],
  ["salt", "condiments & spices", "g", 999, null, null],
  ["black pepper", "condiments & spices", "g", 999, null, null],
  ["chili flakes", "condiments & spices", "g", 720, null, null],
  ["cumin", "condiments & spices", "g", 720, null, null],
  ["paprika", "condiments & spices", "g", 720, null, null],
  ["curry powder", "condiments & spices", "g", 720, null, null],
  ["dried oregano", "condiments & spices", "g", 720, null, null],
  ["cinnamon", "condiments & spices", "g", 720, null, null],
];
