// Seed recipe library. Ingredient names must exactly match catalog.ts entries
// (seed.ts throws otherwise). `opt: true` marks pantry staples and garnishes —
// they never count against coverage or block "ready to cook".

export interface SeedIngredient {
  name: string;
  qty: number | null;
  unit: string | null;
  opt?: boolean;
  prep?: string;
}

export interface SeedRecipe {
  name: string;
  description: string;
  minutes: number;
  servings: number;
  tags: string[];
  steps: string[];
  ings: SeedIngredient[];
}

const i = (
  name: string,
  qty: number | null = null,
  unit: string | null = null,
  opt = false,
  prep?: string,
): SeedIngredient => ({ name, qty, unit, opt, prep });

export const RECIPES: SeedRecipe[] = [
  {
    name: "Spinach & Feta Frittata",
    description: "A ten-minute oven frittata that swallows an entire bag of wilting spinach.",
    minutes: 25,
    servings: 4,
    tags: ["vegetarian", "breakfast", "greens-rescue"],
    steps: [
      "Preheat the broiler. Whisk eggs with milk, salt, and pepper.",
      "Soften the onion in an oven-safe skillet, then wilt the spinach down.",
      "Pour in the eggs, scatter the feta, and cook until the edges set.",
      "Finish under the broiler until puffed and golden, about 3 minutes.",
    ],
    ings: [
      i("eggs", 8, "each"),
      i("spinach", 150, "g"),
      i("feta", 100, "g", false, "crumbled"),
      i("onion", 0.5, "each", false, "thinly sliced"),
      i("milk", 60, "ml"),
      i("olive oil", 1, "tbsp", true),
      i("salt", null, null, true),
      i("black pepper", null, null, true),
    ],
  },
  {
    name: "Weeknight Chicken Stir-fry",
    description: "Hot pan, ten minutes, and whatever vegetables are closest to the edge.",
    minutes: 20,
    servings: 3,
    tags: ["chicken", "quick", "one-pan"],
    steps: [
      "Slice chicken thin; toss with half the soy sauce.",
      "Stir-fry chicken in a ripping-hot pan until just cooked; set aside.",
      "Stir-fry pepper and broccoli 3 minutes, then add garlic and ginger.",
      "Return chicken with remaining soy and sesame oil; serve over rice, topped with scallions.",
    ],
    ings: [
      i("chicken breast", 450, "g", false, "sliced thin"),
      i("bell pepper", 1, "each", false, "sliced"),
      i("broccoli", 1, "each", false, "cut into florets"),
      i("garlic", 3, "clove", false, "minced"),
      i("ginger", 0.5, "each", false, "grated"),
      i("soy sauce", 3, "tbsp"),
      i("rice", 300, "g"),
      i("sesame oil", 1, "tsp", true),
      i("scallions", 0.5, "bunch", true, "sliced"),
    ],
  },
  {
    name: "Creamy Mushroom Pasta",
    description: "Browned mushrooms, cream, and parmesan — the classic fridge-drawer rescue.",
    minutes: 25,
    servings: 3,
    tags: ["vegetarian", "pasta", "comfort"],
    steps: [
      "Cook pasta in well-salted water; reserve a cup of pasta water.",
      "Brown mushrooms hard in butter — don't crowd the pan.",
      "Add garlic and thyme, then cream; simmer 2 minutes.",
      "Toss with pasta, parmesan, and splashes of pasta water until glossy.",
    ],
    ings: [
      i("dried pasta", 300, "g"),
      i("mushrooms", 300, "g", false, "sliced"),
      i("heavy cream", 200, "ml"),
      i("garlic", 3, "clove", false, "minced"),
      i("parmesan", 60, "g", false, "grated"),
      i("butter", 30, "g"),
      i("fresh thyme", 0.25, "bunch", true),
      i("salt", null, null, true),
    ],
  },
  {
    name: "Shakshuka",
    description: "Eggs poached in spiced tomato — uses up peppers, onions, and the feta corner.",
    minutes: 30,
    servings: 2,
    tags: ["vegetarian", "breakfast", "one-pan"],
    steps: [
      "Soften onion and bell pepper in olive oil; add garlic, cumin, paprika.",
      "Add canned tomatoes, simmer 10 minutes until thick.",
      "Make wells and crack in the eggs; cover and cook until whites set.",
      "Scatter feta, and serve with bread for dragging through the sauce.",
    ],
    ings: [
      i("eggs", 4, "each"),
      i("canned tomatoes", 1, "can"),
      i("bell pepper", 1, "each", false, "diced"),
      i("onion", 1, "each", false, "diced"),
      i("garlic", 2, "clove"),
      i("cumin", 1, "tsp"),
      i("paprika", 1, "tsp"),
      i("feta", 50, "g", true, "crumbled"),
      i("bread", 4, "slice", true, "toasted"),
      i("olive oil", 2, "tbsp", true),
    ],
  },
  {
    name: "Banana Oat Pancakes",
    description: "Spotty bananas become Sunday breakfast. Blender batter, no flour needed.",
    minutes: 20,
    servings: 2,
    tags: ["vegetarian", "breakfast", "sweet"],
    steps: [
      "Blend bananas, oats, eggs, milk, and cinnamon until smooth; rest 5 minutes.",
      "Cook small pancakes in butter over medium heat, 2 minutes a side.",
      "Stack and finish with honey.",
    ],
    ings: [
      i("banana", 2, "each", false, "very ripe"),
      i("rolled oats", 100, "g"),
      i("eggs", 2, "each"),
      i("milk", 120, "ml"),
      i("cinnamon", 0.5, "tsp"),
      i("butter", 20, "g"),
      i("honey", null, null, true),
    ],
  },
  {
    name: "Seared Salmon with Asparagus",
    description: "Fish waits for no one. Crisp skin, lemon butter, one pan of asparagus.",
    minutes: 20,
    servings: 2,
    tags: ["fish", "quick", "low-carb"],
    steps: [
      "Pat salmon dry, season, and sear skin-side down 4 minutes; flip for 2 more.",
      "Rest the fish; sauté asparagus in the same pan with garlic.",
      "Add butter and a big squeeze of lemon; spoon over everything.",
    ],
    ings: [
      i("salmon fillet", 300, "g"),
      i("asparagus", 1, "bunch", false, "trimmed"),
      i("lemons", 1, "each"),
      i("garlic", 2, "clove"),
      i("butter", 30, "g"),
      i("olive oil", 1, "tbsp", true),
      i("salt", null, null, true),
    ],
  },
  {
    name: "Everything Fried Rice",
    description: "Day-old rice plus the vegetable drawer's stragglers. The original food-waste recipe.",
    minutes: 15,
    servings: 3,
    tags: ["vegetarian", "quick", "rescue-anything"],
    steps: [
      "Scramble eggs in a hot wok; set aside.",
      "Fry carrots 2 minutes, then peas, garlic, and the white parts of the scallions.",
      "Add cooked rice, pressing it into the hot surface to crisp.",
      "Season with soy and sesame oil; fold in eggs and scallion greens.",
    ],
    ings: [
      i("rice", 400, "g", false, "cooked and cooled"),
      i("eggs", 3, "each"),
      i("carrots", 150, "g", false, "diced"),
      i("frozen peas", 150, "g"),
      i("scallions", 1, "bunch", false, "sliced"),
      i("garlic", 2, "clove"),
      i("soy sauce", 2, "tbsp"),
      i("sesame oil", 1, "tsp"),
      i("ginger", 0.25, "each", true, "grated"),
    ],
  },
  {
    name: "Chicken Caesar Salad",
    description: "Torn stale bread makes the best croutons; romaine on its last week makes the salad.",
    minutes: 25,
    servings: 2,
    tags: ["chicken", "salad"],
    steps: [
      "Toast torn bread in olive oil until golden — instant croutons.",
      "Sear seasoned chicken breast; rest, then slice.",
      "Whisk mayonnaise, dijon, lemon juice, and grated parmesan into a quick dressing.",
      "Toss romaine with dressing; top with chicken, croutons, more parmesan.",
    ],
    ings: [
      i("romaine lettuce", 1, "each", false, "chopped"),
      i("chicken breast", 300, "g"),
      i("bread", 3, "slice", false, "torn"),
      i("parmesan", 40, "g", false, "grated"),
      i("lemons", 0.5, "each", false, "juiced"),
      i("mayonnaise", 60, "g"),
      i("dijon mustard", 1, "tsp"),
      i("olive oil", 2, "tbsp", true),
    ],
  },
  {
    name: "Tomato Basil Soup",
    description: "Fresh tomatoes going soft plus a can for body. Basil rescues itself.",
    minutes: 35,
    servings: 4,
    tags: ["vegetarian", "soup", "comfort"],
    steps: [
      "Soften onion and garlic in olive oil.",
      "Add chopped fresh tomatoes and the canned tomatoes; simmer 20 minutes.",
      "Blend smooth with most of the basil; stir in cream.",
      "Season, and serve with toasted bread.",
    ],
    ings: [
      i("tomatoes", 4, "each", false, "chopped"),
      i("canned tomatoes", 1, "can"),
      i("onion", 1, "each"),
      i("garlic", 3, "clove"),
      i("fresh basil", 0.5, "bunch"),
      i("heavy cream", 100, "ml"),
      i("chicken stock", 500, "ml"),
      i("bread", 4, "slice", true, "toasted"),
      i("olive oil", 2, "tbsp", true),
    ],
  },
  {
    name: "Weeknight Beef Tacos",
    description: "Ground beef won't wait past tomorrow — tacos make sure it doesn't have to.",
    minutes: 20,
    servings: 3,
    tags: ["beef", "quick", "family"],
    steps: [
      "Brown the beef hard; push aside and soften the onion in the same pan.",
      "Season with cumin and paprika; splash of water to make it saucy.",
      "Warm tortillas. Build with beef, cheddar, lettuce, tomato, sour cream.",
      "Finish with lime.",
    ],
    ings: [
      i("ground beef", 450, "g"),
      i("tortillas", 6, "each"),
      i("onion", 1, "each", false, "diced"),
      i("cheddar", 100, "g", false, "grated"),
      i("romaine lettuce", 0.5, "each", false, "shredded"),
      i("tomatoes", 2, "each", false, "diced"),
      i("cumin", 2, "tsp"),
      i("paprika", 1, "tsp"),
      i("limes", 1, "each", true),
      i("sour cream", 60, "g", true),
    ],
  },
  {
    name: "Coconut Chicken Curry",
    description: "Chicken thighs and tired vegetables simmered soft in coconut milk.",
    minutes: 40,
    servings: 4,
    tags: ["chicken", "curry", "one-pot"],
    steps: [
      "Brown chicken thighs; set aside.",
      "Soften onion, garlic, and ginger; bloom the curry powder 1 minute.",
      "Add coconut milk, chicken, and vegetables; simmer 20 minutes.",
      "Serve over rice with cilantro and lime.",
    ],
    ings: [
      i("chicken thighs", 500, "g"),
      i("coconut milk", 1, "can"),
      i("onion", 1, "each"),
      i("garlic", 3, "clove"),
      i("ginger", 0.5, "each", false, "grated"),
      i("curry powder", 2, "tbsp"),
      i("bell pepper", 1, "each", false, "sliced"),
      i("zucchini", 1, "each", false, "chunked"),
      i("rice", 300, "g"),
      i("cilantro", 0.5, "bunch", true),
      i("limes", 1, "each", true),
    ],
  },
  {
    name: "Skillet Margherita Pizza",
    description: "Pizza dough has a short fridge life — mozzarella and basil, hot oven, done.",
    minutes: 25,
    servings: 2,
    tags: ["vegetarian", "comfort"],
    steps: [
      "Heat the oven to its maximum with a skillet or steel inside.",
      "Stretch the dough; top with crushed canned tomatoes and torn mozzarella.",
      "Bake until blistered, 8–10 minutes.",
      "Finish with basil, olive oil, and parmesan.",
    ],
    ings: [
      i("pizza dough", 1, "each"),
      i("fresh mozzarella", 125, "g", false, "torn"),
      i("canned tomatoes", 0.5, "can", false, "crushed and drained"),
      i("fresh basil", 0.25, "bunch"),
      i("olive oil", 1, "tbsp", true),
      i("parmesan", 20, "g", true),
    ],
  },
  {
    name: "Greek Salad",
    description: "No cooking at all — cucumbers and tomatoes at their peak (or just past it).",
    minutes: 15,
    servings: 2,
    tags: ["vegetarian", "salad", "no-cook"],
    steps: [
      "Chunk cucumber, tomatoes, and red onion — big, rustic pieces.",
      "Add olives and thick slabs of feta.",
      "Dress with olive oil, lemon, oregano, and salt.",
    ],
    ings: [
      i("cucumber", 1, "each"),
      i("tomatoes", 3, "each"),
      i("red onion", 0.5, "each", false, "thinly sliced"),
      i("feta", 100, "g"),
      i("kalamata olives", 60, "g"),
      i("dried oregano", 1, "tsp"),
      i("lemons", 0.5, "each"),
      i("olive oil", 3, "tbsp", true),
    ],
  },
  {
    name: "Berry Yogurt Parfait",
    description: "Berries on the brink layered with yogurt and toasted oats.",
    minutes: 10,
    servings: 2,
    tags: ["vegetarian", "breakfast", "no-cook", "sweet"],
    steps: [
      "Toast oats in a dry pan with a drizzle of honey until golden.",
      "Layer yogurt, berries, and oats in glasses.",
      "Finish with more honey.",
    ],
    ings: [
      i("greek yogurt", 300, "g"),
      i("strawberries", 150, "g", false, "hulled and halved"),
      i("blueberries", 100, "g"),
      i("rolled oats", 60, "g"),
      i("honey", 2, "tbsp"),
    ],
  },
  {
    name: "Roasted Veggie Grain Bowl",
    description: "Roast whatever's wilting, pile it on quinoa, add chickpeas and lemon yogurt.",
    minutes: 40,
    servings: 3,
    tags: ["vegetarian", "bowl", "meal-prep"],
    steps: [
      "Roast sweet potato and broccoli with cumin at 220°C until browned.",
      "Cook quinoa; drain and rinse chickpeas.",
      "Stir lemon juice into yogurt for the sauce.",
      "Bowl it up: quinoa, vegetables, chickpeas, yogurt, more lemon.",
    ],
    ings: [
      i("quinoa", 200, "g"),
      i("sweet potatoes", 2, "each", false, "cubed"),
      i("broccoli", 1, "each", false, "florets"),
      i("chickpeas", 1, "can"),
      i("lemons", 1, "each"),
      i("cumin", 1, "tsp"),
      i("greek yogurt", 100, "g", true),
      i("olive oil", 2, "tbsp", true),
    ],
  },
  {
    name: "Garlic Butter Shrimp Pasta",
    description: "Frozen shrimp, fresh parsley, and a lot of garlic. Fifteen honest minutes.",
    minutes: 18,
    servings: 2,
    tags: ["fish", "pasta", "quick"],
    steps: [
      "Cook pasta; reserve some water.",
      "Sizzle garlic and chili flakes in butter; add shrimp until just pink.",
      "Toss with pasta, lemon juice, and parsley, loosening with pasta water.",
    ],
    ings: [
      i("shrimp", 300, "g", false, "peeled"),
      i("dried pasta", 200, "g"),
      i("garlic", 4, "clove", false, "sliced"),
      i("butter", 50, "g"),
      i("lemons", 1, "each"),
      i("parsley", 0.5, "bunch", false, "chopped"),
      i("chili flakes", 0.5, "tsp", true),
    ],
  },
  {
    name: "Chicken Noodle Soup",
    description: "The soup that clears the crisper: carrots, celery, and chicken that must go.",
    minutes: 40,
    servings: 4,
    tags: ["chicken", "soup", "comfort"],
    steps: [
      "Sweat onion, carrots, and celery in olive oil until soft.",
      "Add stock and chicken; simmer 15 minutes, then shred the chicken.",
      "Add pasta and thyme; cook until tender.",
      "Season and shower with parsley.",
    ],
    ings: [
      i("chicken breast", 300, "g"),
      i("chicken stock", 1000, "ml"),
      i("carrots", 150, "g", false, "sliced"),
      i("celery", 0.5, "each", false, "sliced"),
      i("onion", 1, "each", false, "diced"),
      i("dried pasta", 150, "g"),
      i("fresh thyme", 0.25, "bunch", true),
      i("parsley", 0.25, "bunch", true),
    ],
  },
  {
    name: "Avocado Toast with Jammy Eggs",
    description: "Avocados ripen on their own schedule. Meet them there.",
    minutes: 12,
    servings: 2,
    tags: ["vegetarian", "breakfast", "quick"],
    steps: [
      "Boil eggs 7 minutes; ice bath, peel, halve.",
      "Toast the bread; smash avocado on top with lemon and salt.",
      "Add eggs and chili flakes.",
    ],
    ings: [
      i("bread", 4, "slice"),
      i("avocado", 2, "each"),
      i("eggs", 4, "each"),
      i("lemons", 0.5, "each", true),
      i("chili flakes", null, null, true),
      i("salt", null, null, true),
    ],
  },
  {
    name: "Zucchini Feta Fritters",
    description: "Two zucchini disappear into crisp fritters. Dill and sour cream on the side.",
    minutes: 30,
    servings: 3,
    tags: ["vegetarian", "snack"],
    steps: [
      "Grate zucchini, salt it, and squeeze out as much water as you can.",
      "Mix with eggs, flour, feta, and sliced scallions.",
      "Fry spoonfuls in olive oil until deeply golden on both sides.",
      "Serve with sour cream and dill.",
    ],
    ings: [
      i("zucchini", 2, "each", false, "grated and squeezed"),
      i("eggs", 2, "each"),
      i("flour", 60, "g"),
      i("feta", 80, "g", false, "crumbled"),
      i("scallions", 0.5, "bunch", false, "sliced"),
      i("olive oil", 3, "tbsp", true),
      i("sour cream", 100, "g", true),
      i("fresh dill", 0.25, "bunch", true),
    ],
  },
  {
    name: "Sausage & Pepper Skillet",
    description: "Sausages, peppers, and potatoes in one pan — the fridge clean-out classic.",
    minutes: 35,
    servings: 3,
    tags: ["pork", "one-pan", "comfort"],
    steps: [
      "Brown the sausages; set aside.",
      "Fry potatoes until crisp-edged, then add peppers, onion, and garlic.",
      "Add canned tomatoes and the sausages back; simmer 10 minutes.",
    ],
    ings: [
      i("italian sausage", 400, "g"),
      i("bell pepper", 2, "each", false, "sliced"),
      i("onion", 1, "each", false, "sliced"),
      i("garlic", 3, "clove"),
      i("potatoes", 3, "each", false, "cubed"),
      i("canned tomatoes", 1, "can"),
      i("olive oil", 2, "tbsp", true),
    ],
  },
  {
    name: "Mushroom Risotto",
    description: "Slow-stirred arborio with browned mushrooms — worth every minute.",
    minutes: 45,
    servings: 3,
    tags: ["vegetarian", "comfort", "project"],
    steps: [
      "Brown mushrooms in butter; set aside.",
      "Soften onion and garlic; toast the rice 2 minutes.",
      "Add warm stock a ladle at a time, stirring, about 20 minutes.",
      "Fold in mushrooms, parmesan, and a last knob of butter.",
    ],
    ings: [
      i("arborio rice", 300, "g"),
      i("mushrooms", 250, "g", false, "sliced"),
      i("onion", 1, "each", false, "finely diced"),
      i("garlic", 2, "clove"),
      i("parmesan", 60, "g", false, "grated"),
      i("butter", 60, "g"),
      i("chicken stock", 1000, "ml", false, "kept warm"),
    ],
  },
  {
    name: "BLT on Toast",
    description: "When the lettuce and tomatoes are ready, the bacon is always willing.",
    minutes: 15,
    servings: 2,
    tags: ["pork", "sandwich", "quick"],
    steps: [
      "Cook bacon until crisp.",
      "Toast bread; spread generously with mayonnaise.",
      "Layer lettuce, thick tomato slices (salted), and bacon.",
    ],
    ings: [
      i("bacon", 150, "g"),
      i("bread", 4, "slice"),
      i("romaine lettuce", 0.5, "each"),
      i("tomatoes", 2, "each", false, "thickly sliced"),
      i("mayonnaise", 40, "g"),
    ],
  },
  {
    name: "Lemon Baked Cod with Green Beans",
    description: "Sheet-pan white fish before its two-day clock runs out.",
    minutes: 25,
    servings: 2,
    tags: ["fish", "sheet-pan", "low-carb"],
    steps: [
      "Toss green beans with olive oil on a sheet pan; roast 10 minutes at 200°C.",
      "Nestle in the cod with lemon slices, garlic, and butter.",
      "Roast 10–12 minutes more until the fish flakes.",
    ],
    ings: [
      i("cod fillet", 300, "g"),
      i("green beans", 250, "g", false, "trimmed"),
      i("lemons", 1, "each", false, "sliced"),
      i("garlic", 2, "clove"),
      i("butter", 30, "g"),
      i("paprika", 0.5, "tsp", true),
      i("olive oil", 1, "tbsp", true),
    ],
  },
  {
    name: "Crispy Tofu Stir-fry",
    description: "Tofu and the stiffer vegetables — carrots, broccoli — under a glossy soy glaze.",
    minutes: 25,
    servings: 3,
    tags: ["vegan-ish", "quick", "one-pan"],
    steps: [
      "Press tofu, cube it, and fry until golden on all sides; set aside.",
      "Stir-fry broccoli and carrots 4 minutes; add garlic and ginger.",
      "Return tofu with soy sauce, sriracha, and sesame oil; serve over rice.",
    ],
    ings: [
      i("tofu", 400, "g", false, "pressed and cubed"),
      i("broccoli", 1, "each", false, "florets"),
      i("carrots", 150, "g", false, "sliced"),
      i("garlic", 3, "clove"),
      i("ginger", 0.5, "each", false, "grated"),
      i("soy sauce", 3, "tbsp"),
      i("rice", 300, "g"),
      i("sriracha", 1, "tbsp", true),
      i("sesame oil", 1, "tsp", true),
    ],
  },
];
